name: another workflow
on:
 push:
  branches: ["live"]
  
 workflow_dispatch:
 
jobs: 
# configure port numbers
 port_configuration: # port are configured to forward the default http and https port's trafic to the port 8080. 
     runs-on: self-hosted
     steps:
       - run : sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
       - run : sudo iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-port 8080
 dependency_installation : 
     runs-on: self-hosted 
     steps:
       # installing java and maven.
       - uses: actions/setup-java@v3
         with:
          distribution: 'oracle'
          java-version: '17'
 deploy:
     runs-on: self-hosted
     needs: [port_configuration, dependency_installation ]
     steps:
         - run : sudo apt-get install cowsay -y
        #- uses: actions/checkout@v3
        #- run: echo "hello word" 
        #- run: npm i
        #- run: npm start
