name: another workflow
on:
 push:
  branches: ["live"]
  
 workflow_dispatch:
 
jobs:
 deploy:
     runs-on: self-hosted

     steps:
         - uses: actions/checkout@v3
         - run: echo "hello word" 
         - run: npm i
         - run: npm start
